### PR TITLE
fix #156, negative hits when remaining 0

### LINKED ISSUE #156: negative hits is not processed when remaining equals 0
Setting negative `hits` values does not work when `remaining` is already at 0.

In our use-case, we sometimes set the `hits` property in the rate limit request to negative values.
This works well by default, for example, let us suppose that we have the following request, with the current value of `remaining` being 5:
```json
{
    "requests":[
        {
            "name": "requests_per_sec",
            "unique_key": "account.id=1234",
            "hits": -1,
            "duration": 60000,
            "limit": 10
        }
    ]
}
```

This results in the `remaining` increasing by one as expected:
```json
{
  "responses":[
    {
      "status": "UNDER_LIMIT",
      "limit": "10",
      "remaining": "6",
      "reset_time": "1551309219226"
    }
  ]
}
```

However, if the request is done when the value of `remaining` is 0, the negative `hits` do not get processed. The response always returns `'OVER_LIMIT'`, even though we are trying to increase the `remaining` tokens by specifying a negative value.

In case of the `tokenBucket` algorithm for example, the culprit can be found here:
https://github.com/mailgun/gubernator/blob/1803ac23f4a6b5f0028e2dff6c8a34069344f181/algorithms.go#L179-L185

The fix would be relatively straightforward:
```golang
// If we are already at the limit.
if rl.Remaining == 0 && r.Hits > 0 {
	span.AddEvent("Already over the limit")
	overLimitCounter.Add(1)
	rl.Status = Status_OVER_LIMIT
	t.Status = rl.Status
	return rl, nil
}
```

I will try to make a pull request with the fix for the various algorithms.

### PR DESCRIPTION
**Pull request by Loosetooth**
This pull request fixes #156.

It's a simple change in both the tokenBucket and leakyBucket algorithms.
Unit tests for both changes were added.

### CODE REVIEW

**Review by Baliedge — APPROVED** [review]
LGTM 👍🏻

**Review by Baliedge — CHANGES_REQUESTED** [review]
@Loosetooth, your new unit tests are failing.  Please take a look.

**Comment by Loosetooth** [comment]
Thanks for letting me know.
I'm having a bit of an annoying problem with the tests. I'm using VSCode as my IDE, and I can run the tests manually by pressing the "play" button next to the test. For example, running the `TestTokenBucketNegativeHits` runs the following command which **passes**:
```
Running tool: /usr/local/go/bin/go test -timeout 30s -run ^TestTokenBucketNegativeHits$ github.com/mailgun/gubernator/v2

=== RUN   TestTokenBucketNegativeHits
=== RUN   TestTokenBucketNegativeHits/remaining_should_be_three
=== RUN   TestTokenBucketNegativeHits/remaining_should_be_four_and_under_limit
=== RUN   TestTokenBucketNegativeHits/remaining_should_be_0_and_under_limit
=== RUN   TestTokenBucketNegativeHits/remaining_should_be_1_and_under_limit
--- PASS: TestTokenBucketNegativeHits (0.01s)
    --- PASS: TestTokenBucketNegativeHits/remaining_should_be_three (0.00s)
    --- PASS: TestTokenBucketNegativeHits/remaining_should_be_four_and_under_limit (0.00s)
    --- PASS: TestTokenBucketNegativeHits/remaining_should_be_0_and_under_limit (0.00s)
    --- PASS: TestTokenBucketNegativeHits/remaining_should_be_1_and_under_limit (0.00s)
PASS
ok      github.com/mailgun/gubernator/v2        (cached)


> Test run finished at 10/20/2022, 9:24:46 AM <
```

So I thought my tests were working :D

However, when I run `make test` I get the same errors as the github jobs is showing. Any idea what might cause this inconsistency?

**Comment by Loosetooth** [comment]
I figured out what the problem was, I used the same `Name` and `UniqueKey` properties as another existing test, thus causing this state to be saved between tests. Running with the "play" button of course would not have the state of the test that was run earlier.

It should be fixed now.

File: functional_test.go [hunk 1]
```diff
@@ -341,8 +341,8 @@ func TestTokenBucketNegativeHits(t *testing.T) {
 			resp, err := client.GetRateLimits(context.Background(), &guber.GetRateLimitsReq{
 				Requests: []*guber.RateLimitReq{
 					{
-						Name:      "test_token_bucket",
-						UniqueKey: "account:1234",
+						Name:      "test_token_bucket_negative",
+						UniqueKey: "account:12345",
```
Comment (Baliedge) [inline functional_test.go:345]: Now that I see this was a problem, I would recommend not using arbitrary key names that could be reused by other tests.  Instead of `12345` create a const value with a unique descriptive key name.

**Review by Baliedge — CHANGES_REQUESTED** [review]

File: functional_test.go (hunk 1 above)
Comment (Baliedge) [reply functional_test.go:345]: nvm, you already did with a unique `Name`.  No problem here.

**Review by Baliedge — APPROVED** [review]
🍩
