### PR TITLE
ensure we continue after peers (1 or more) were closed successfully

### LINKED ISSUE #34: Peer detection not detecting POD restarts and incorrect rate limit results
- Minikube + locally build gubernator 0.7.1 docker container 
- in default namespace with cluster admin permissions, deployment with 3 instances of gubernator (https://github.com/mailgun/gubernator#kubernetes). No other changes were made to the deployment.

So far all is fine...
- Calling `/v1/HealthCheck` on all 3 endpoints will return `{"status":"healthy","peer_count":3}`
- Ratelimit requests (token) will give the expected result (remaining/throttled)
- Running `kubectl logs <pod> -f` on 2 of the 3 pods will show something like the following:

```
time="2019-12-13T12:51:54Z" level=debug msg="Debug enabled"
time="2019-12-13T12:51:54Z" level=debug msg="K8s peer pool config found"
(main.ServerConfig) {
 GRPCListenAddress: (string) (len=10) "0.0.0.0:81",
 EtcdAdvertiseAddress: (string) (len=12) "127.0.0.1:81",
 HTTPListenAddress: (string) (len=10) "0.0.0.0:80",
 EtcdKeyPrefix: (string) (len=17) "/gubernator-peers",
 CacheSize: (int) 50000,
 EtcdConf: (clientv3.Config) {
  Endpoints: ([]string) (len=1 cap=1) {
   (string) (len=14) "localhost:2379"
  },
  AutoSyncInterval: (time.Duration) 0s,
  DialTimeout: (time.Duration) 5s,
  DialKeepAliveTime: (time.Duration) 0s,
  DialKeepAliveTimeout: (time.Duration) 0s,
  MaxCallSendMsgSize: (int) 0,
  MaxCallRecvMsgSize: (int) 0,
  TLS: (*tls.Config)(<nil>),
  Username: (string) "",
  Password: (string) "",
  RejectOldCluster: (bool) false,
  DialOptions: ([]grpc.DialOption) <nil>,
  Context: (context.Context) <nil>
 },
 Behaviors: (gubernator.BehaviorConfig) {
  BatchTimeout: (time.Duration) 0s,
  BatchWait: (time.Duration) 0s,
  BatchLimit: (int) 0,
  GlobalSyncWait: (time.Duration) 0s,
  GlobalTimeout: (time.Duration) 0s,
  GlobalBatchLimit: (int) 0
 },
 K8PoolConf: (gubernator.K8sPoolConfig) {
  OnUpdate: (gubernator.UpdateFunc) <nil>,
  Namespace: (string) (len=7) "default",
  Selector: (string) (len=14) "app=gubernator",
  PodIP: (string) (len=11) "172.17.0.18",
  PodPort: (string) (len=2) "81",
  Enabled: (bool) true
 }
}
time="2019-12-13T12:51:54Z" level=info msg="Gubernator Listening on 0.0.0.0:81 ..." category=server
time="2019-12-13T12:51:54Z" level=debug msg="Queue (Add) 'default/gubernator' - %!s(<nil>)"
time="2019-12-13T12:51:54Z" level=debug msg="Fetching peer list from endpoints API"
time="2019-12-13T12:51:54Z" level=info msg="Peers updated" category=gubernator peers="[]"
time="2019-12-13T12:51:54Z" level=info msg="HTTP Gateway Listening on 0.0.0.0:80 ..." category=server
time="2019-12-13T12:51:55Z" level=debug msg="Queue (Update) 'default/gubernator' - %!s(<nil>)"
time="2019-12-13T12:51:55Z" level=debug msg="Fetching peer list from endpoints API"
time="2019-12-13T12:51:55Z" level=debug msg="Peer: {Address:172.17.0.19:81 IsOwner:false}\n"
time="2019-12-13T12:51:55Z" level=info msg="Peers updated" category=gubernator peers="[{172.17.0.19:81 false}]"
time="2019-12-13T12:51:57Z" level=debug msg="Queue (Update) 'default/gubernator' - %!s(<nil>)"
time="2019-12-13T12:51:57Z" level=debug msg="Fetching peer list from endpoints API"
time="2019-12-13T12:51:57Z" level=debug msg="Peer: {Address:172.17.0.18:81 IsOwner:true}\n"
time="2019-12-13T12:51:57Z" level=debug msg="Peer: {Address:172.17.0.19:81 IsOwner:false}\n"
time="2019-12-13T12:51:57Z" level=info msg="Peers updated" category=gubernator peers="[{172.17.0.18:81 true} {172.17.0.19:81 false}]"
time="2019-12-13T12:51:58Z" level=debug msg="Queue (Update) 'default/gubernator' - %!s(<nil>)"
time="2019-12-13T12:51:58Z" level=debug msg="Fetching peer list from endpoints API"
time="2019-12-13T12:51:58Z" level=debug msg="Peer: {Address:172.17.0.13:81 IsOwner:false}\n"
time="2019-12-13T12:51:58Z" level=debug msg="Peer: {Address:172.17.0.18:81 IsOwner:true}\n"
time="2019-12-13T12:51:58Z" level=debug msg="Peer: {Address:172.17.0.19:81 IsOwner:false}\n"
time="2019-12-13T12:51:58Z" level=info msg="Peers updated" category=gubernator peers="[{172.17.0.13:81 false} {172.17.0.18:81 true} {172.17.0.19:81 false}]"

```

Now.......

- kill the pod where you are not monitoring the logs.
- The 2 remaining PODs will detect the peer deletion but will never detect the 3rd POD being restarted.
- Only the following is shown in the logs

```
time="2019-12-13T12:53:25Z" level=debug msg="Queue (Update) 'default/gubernator' - %!s(<nil>)"
time="2019-12-13T12:53:25Z" level=debug msg="Fetching peer list from endpoints API"
time="2019-12-13T12:53:25Z" level=debug msg="Peer: {Address:172.17.0.13:81 IsOwner:false}\n"
time="2019-12-13T12:53:25Z" level=debug msg="Peer: {Address:172.17.0.18:81 IsOwner:true}\n"
time="2019-12-13T12:53:25Z" level=info msg="Peers updated" category=gubernator peers="[{172.17.0.13:81 false} {172.17.0.18:81 true}]"

```

Calling `/v1/HealthCheck` on all 3 endpoints will return `{"status":"healthy","peer_count":2}` on the 2 remaining PODS and `{"status":"healthy","peer_count":3}` on the restarted POD.

This is already messing up the getratelimit requests. 

To make it worse.......

Wait for the the following message to appear in the 2 PODs that were not killed.

```
W1213 13:17:56.913021       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: watch of *v1.Endpoints ended with: too old resource version: 398370 (399065)
```

After this message delete 1 of the 2 remaining PODs. I would expect that the other POD would detect the deletion but this is also not the case.

I would expect that in both POD deletion scenarios (with and without the `watch of *v1.Endpoints ended with: too old resource version` message) all  `/v1/HealthCheck`  on all 3 POD instances always to return  `{"status":"healthy","peer_count":3}` (except for the time a POD is actually re-starting). And more importantly that the ratelimit requests keep on returning the correct results (remaining/throttled) after POD restarts.

Without this fixed using more that 1 instance of gubernator is not working on kubernetes

### PR DESCRIPTION
**Pull request by aligthart**
This is supposed to fix #34

This is my first ever golang code change so no idea if there is another better way to fix this.

Issue was that the wait statement never completed/returned and as a result new endpoint changes ended up as a pending notification as the current notification never completed: https://github.com/kubernetes/client-go/blob/master/tools/cache/shared_informer.go#L638

So this fix explicitly reduces the waitcount after shutting down the peer.
While testing a scenario with stopping multiple instances (2 out of 3) it was also needed to first set the wait count to 2 before starting the go routines.

### CODE REVIEW

File: gubernator.go [hunk 1]
```diff
@@ -359,15 +359,18 @@ func (s *Instance) SetPeers(peers []PeerInfo) {
...
-			}()
 		}
 	}
 
+	for _, p := range shutdownPeers {
+        go func() {
+            err := p.Shutdown(ctx, &wg)
+            if err != nil {
+                log.WithError(err).WithField("peer", p).Error("while shutting down peer")
+            }
```
Comment (thrawn01) [inline gubernator.go]: the wg.Done() should go on the next line, after this `}` . No need to pass the `wg` into `Shutdown()` right? This is the only place `Shutdown()` is called inside a go routine.

Comment (aligthart) [reply gubernator.go]: Thanks. I made the suggested code change. I only checked that it compiled. To be honest I'm not sure when I have time to test this as I destroyed my entire test setup just before the Christmas holidays.

We were running a POC with gubernator as an nginx sidecar using the ngix helm chart with some lua code snippets and ingress annotations. This was successful although we also ran into https://github.com/mailgun/gubernator/issues/23 which is now also closed I see. We are now running some other throttling POCs.

Let me know if you think it is safe to pull this request as is. Its also fine by me if you want to incorporate this change in another branch if that is more convenient.

**Comment by aligthart** [comment]
:+1:
